test_that("histogram with mean line is generated properly", {
  data(iris)
  p <- histredline(iris, Sepal.Length)
  expect_true(dplyr::is.ggplot(p))
  expect_identical(class(test.hist$layers[[1]]$geom)[1], "GeomBar")
  expect_identical(class(test.hist$layers[[2]]$geom)[1], "GeomVline")
  expect_error(print(histredline(iris, Species)), NA)
  rm(iris)
  rm(p)
})
